name: Generate APK Test1
on:
  workflow_dispatch:
    inputs:

      versionCode:
        description: 'VersionCode (Integer)'
        required: true
        default: '1'

      versionName:
        description: 'Version Name'
        required: true
        default: '1.0'

      desc:
        description: 'Apk Description'
        default: 'Test'

jobs:

  apk:
    name: Generate Debug APK
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Print Params Values
        run: |
          bash update_properties.sh ${{ github.event.inputs.versionCode }} ${{ github.event.inputs.versionName }} ${{ github.event.inputs.desc }} 
      - name: Assemble app debug APK
        run: bash ./gradlew assembleDebug --stacktrace

      - name: Upload app APK
        uses: actions/upload-artifact@v1
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk
